<nav role="navigation" class="navbar navbar-default">
    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">ELAMobile</a>
    </div>

    <div id="navbarCollapse" class="collapse navbar-collapse">
        <?php echo $this->navigation()->menu()->setUlClass('nav navbar-nav')->render() ?>

        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b><span class="glyphicon glyphicon glyphicon-cog"></span> Configuración</b></a>
                <ul id="login-dp" class="dropdown-menu">
                    <li>
                        <a href="login.html" ><span class="glyphicon glyphicon-user"></span> Administrador</a>
                        <a href="<?php echo $this->url(["controller" => "usuarios", "action" => "logout"], "default") ?>">
                            <span class="glyphicon glyphicon-off"></span> Cerrar Sesión</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav> 

<?php if ($this->mensajes): ?>
    <?php foreach ($this->mensajes as $mensaje) : ?>
        <?php
        $mensaje = explode('|', $mensaje);
        $class = 'success';
        if (count($mensaje) > 1) {
            $class = $mensaje[0];
            $mensaje = $mensaje[1];
        } else {
            $mensaje = $mensaje[0];
        }
        ?>
        <div class="label label-<?php echo $class ?>"><?php echo $mensaje ?></div>
    <?php endforeach; ?>
    <div class="clearfix"></div>
    <br />
<?php endif; ?>

