<!--(Botones)-->      
<div class="row">
     </br>
    <div class="col-xs-12 col-sm-4 col-md-offset-4">

       <div class='define'>
        <input id="espacio"     type="button" class="btn btn-primary btn-sm" value="Espacio"  />
        <input id="borrar"      type="button" class="btn btn-primary btn-sm" value="Borrar"  />
        <input id="borrar_todo" type="button" class="btn btn-primary btn-sm" value="Borrar Todo"/>
      </div>

    </div>

</div>

<div class="row">
    <div class="col-xs-12 col-sm-5 col-md-offset-5">
        <input id="cancelar" type="button" class="btn btn-primary btn-sm" value="Cancelar"/>
    </div>
</div>   

