<!--(Botones)-->      
<div class="row">
    </br>
    <div class="col-xs-12 col-sm-12">
        <div class='define'>
            <input id="espacio"     type="button" class="btn btn-primary btn-sm" value="<?php echo __('Espacio') ?>"  />
            <input id="borrar"      type="button" class="btn btn-primary btn-sm" value="<?php echo __('Borrar') ?>"  />
            <input id="borrar_todo" type="button" class="btn btn-primary btn-sm" value="<?php echo __('Borrar Todo') ?>"/>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-5 col-md-offset-5">
        <input id="cancelar" type="button" class="btn btn-primary btn-sm" value="<?php echo __('Cancelar') ?>"/>
    </div>
</div>   

