<?php
$carrito = $this->carrito;
?>
<form method="Post">
    <table class="table table-responsive">
        <tr>
            <th><?php echo __('Licencia') ?></th>
            <th><?php echo __('Precio') ?></th>
            <th><?php echo __('Cantidad') ?></th>
            <th><?php echo __('Subtotal') ?></th>
            <th></th>
        </tr>
        <?php foreach ($this->licencias as $licencia) : ?>
            <tr>
                <td><?php echo $licencia->getNombre() ?></td>
                <td><?php echo $licencia->getPrecio() ?></td>
                <td><input type="number" name="detalle[<?php echo $licencia->getId() ?>]" value="<?php echo $carrito->getCantidadLicencia($licencia) ?>" /></td>
                <td><?php echo $carrito->getPrecioLicencia($licencia) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <button type="submit" class="btn btn-default">
        <?php echo __('Guardar') ?>
    </button>
</form>