<a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'carrito')) ?>" class="btn btn-primary">Carrito</a>
<table class="table">
    <tr>
        <?php if ($this->ocultar_institucion !== true) : ?>
            <th><?php echo __('Institucion') ?></th>
        <?php endif; ?>
        <th><?php echo __('Fecha') ?></th>
        <th><?php echo __('Borrador') ?></th>
        <th><?php echo __('Aprobada') ?></th>
        <th><?php echo __('Precio') ?></th>
        <th><?php echo __('Acciones') ?></th>
    </tr>
    <?php foreach ($this->listado as /* @var $item Model_Row_Compra */ $item) : ?>
        <tr>
            <?php if ($this->ocultar_institucion !== true) : ?>
                <td><?php echo $item->getRazonSocial(); ?></td>
            <?php endif; ?>
            <td><?php echo $item->getFecha(); ?></td>
            <td><?php echo __($item->getBorrador() ? "Si" : "No") ?></td>
            <td><?php echo __($item->getAprobado() ? "Si" : "No") ?></td>
            <td><?php echo $this->currency($item->getPrecio()) ?></td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'ver', 'id' => $item->getId())) ?>">
                    <?php echo __('Ver') ?>
                </a>
                <?php if ($item->getAprobado() == 0) : ?>
                    <a href="<?php echo $this->url(array('action' => 'pagar', 'id' => $item->getId())) ?>" target="_blank">
                        <?php echo __('Pagar') ?>
                    </a>                
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>