<a href="<?php echo $this->url(array('action' => 'carrito')) ?>" class="btn btn-primary">Carrito</a>
<table class="table">
    <tr>
        <td><?php echo __('Fecha') ?></td>
        <td><?php echo __('Borrador') ?></td>
        <td><?php echo __('Precio') ?></td>
        <td><?php echo __('Acciones') ?></td>
    </tr>
    <?php foreach ($this->listado as /* @var $item Model_Row_Compra */ $item) : ?>
        <tr>
            <td><?php echo $item->getFecha(); ?></td>
            <td><?php echo __($item->getBorrador() ? "Si" : "No") ?></td>
            <td><?php echo $item->getPrecio(); ?></td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'modificar', 'id' => $item->getId())) ?>"><?php echo __('Editar') ?></a>
                <a href="<?php echo $this->url(array('action' => 'baja', 'id' => $item->getId())) ?>"><?php echo __('Borrar') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>