<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/controller.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/tablero.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/voz/mespeak.js"></script>
<script type="text/javascript">
    meSpeak.loadConfig("<?php echo $this->baseUrl() ?>/voz/mespeak_config.json");
    meSpeak.loadVoice("<?php echo $this->baseUrl() ?>/voz/voices/es-la.json");
</script>

<?php
/* @var $tablero Model_Row_Tablero */
$tablero = $this->tablero_principal;
?>
<?php if ($tablero != null) : ?>
    <h4><?php echo __('Ingrese mensaje:') ?></h4>
    <header>
        <div class="row"> 
            <div class="col-md-11 col-xs-11">
                <textarea id="mensaje" readonly> </textarea>                          
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1 col-lg-1 col-xs-offset-10 col-sm-offset-10 col-md-offset-10 col-lg-offset-10">
                <img id="voz" src="<?php echo $this->baseUrl() ?>/img/icon-par.jpg" aria-label="Escuchar" data-tooltip="<?php echo __('Escuchar') ?>"  alt="Responsive image" >
            </div>
        </div>
    </header>

    <center>
        <?php
        // Se imprime el tablero realizando
        // la conversion, casteando la instancia de la clase en string (__ToString)
        echo $tablero
        ?>
        <?php echo $this->render('_html/pie_pagina.phtml') ?>
    </center>

    <script type="text/javascript">
        var grupos = <?php echo Zend_Json::encode($tablero->toArrayData()) ?>
    </script>
<?php endif; ?>