<a href="<?php echo $this->url(array('action' => 'alta')) ?>" class="btn btn-primary">
    <?php echo __('Nuevo') ?>
</a>
<table class="table table-hover">
    <thead>
        <tr>
            <th><?php echo __('Nombre') ?></th>
            <th><?php echo __('Acciones') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->listado as $item) : ?>
            <tr<?php echo $item->getSistema() ? ' class="danger"' : '' ?>>
                <td>
                    <?php echo $item->getNombre(); ?>
                </td>
                <td>
                    <a href="<?php echo $this->url(array('action' => 'modificar', 'id' => $item->getId())) ?>"><?php echo __('Editar') ?></a>
                    <a href="<?php echo $this->url(array('action' => 'baja', 'id' => $item->getId())) ?>"><?php echo __('Borrar') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="bg-danger col-md-2"><?php echo __('Roles de sistema') ?></div>