<?php
/* @var $carrito Model_Row_Compra */
$carrito = $this->carrito;
?>
<form method="Post">
    <table class="table table-responsive">
        <thead>
            <tr>
                <th><?php echo __('Licencia') ?></th>
                <th><?php echo __('Precio') ?></th>
                <th><?php echo __('Cantidad') ?></th>
                <th><?php echo __('Subtotal') ?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->licencias as $licencia) : ?>
                <tr>
                    <td><?php echo $licencia->getNombre() ?></td>
                    <td><?php echo $licencia->getPrecio() ?></td>
                    <td><input type="number" data-precio="<?php echo $licencia->getPrecio() ?>" class="cantidad-detalle" name="detalle[<?php echo $licencia->getId() ?>]" value="<?php echo $carrito->getCantidadLicencia($licencia) ?>" /></td>
                    <td class="subtotal"><?php echo $this->currency($carrito->getPrecioLicencia($licencia)) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3"></th>
                <th>
                    <span class="total">
                        <?php echo $this->currency($carrito->getPrecio()) ?>
                    </span>
                </th>
            </tr>
        </tfoot>
    </table>
    <button type="submit" class="btn btn-default">
        <?php echo __('Guardar') ?>
    </button>
    <button type="submit" name="continuar" class="btn btn-default">
        <?php echo __('Pagar') ?>
    </button>
</form>
<script type="text/javascript">
    window.onload = function () {
        $('.cantidad-detalle').on('change', function () {
            var total = 0;
            $('.cantidad-detalle').each(function () {
                var precio = $(this).data('precio');
                var cantidad = $(this).val();
                var subtotal = precio * cantidad;
                total += subtotal;
                var tr = $(this).parents('tr');
                tr.find('.subtotal')
                        .html('$' + parseFloat(Math.round(subtotal * 100) / 100).toFixed(2))
            })

            $('.total').html('$' + parseFloat(Math.round(total * 100) / 100).toFixed(2))

        })
    }
</script>