<a href="<?php echo $this->url(array('action' => 'alta')) ?>" class="btn btn-primary"><?php echo __('Nuevo') ?></a>
<table class="table">
    <tr>
        <td><?php echo __('Razon social') ?></td>
        <td><?php echo __('Acciones') ?></td>
    </tr>
    <?php foreach ($this->listado as $item) : ?>
        <tr>
            <td>
                <?php echo $item->getRazonSocial(); ?>
            </td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'modificar', 'id' => $item->getId())) ?>"><?php echo __('Editar') ?></a>
                <a href="<?php echo $this->url(array('action' => 'baja', 'id' => $item->getId())) ?>"><?php echo __('Borrar') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>