<?php echo $this->error_form ?>
<form action="" method="post">
    <!--Cabecera-->
    <header>
        <div class="row">
            <div class="col-xs-12 col-md-12">
                </br>
                <center><h4>ELAMobile</h4></center>
            </div>
        </div>
    </header>
    <!--Ingreso-->
    </br>
    <div id=BodyContein  class="container">
        <!--Usuario-->
        <div class="row">
            <!--LABEL-->
            <div class="col-md-6 col-md-offset-3 col-xs-12">
                <div class="col-xs-12 col-sm-2">
                </div>
                <!--Caja de texto-->
                <div class="col-xs-12 col-sm-9">
                    <div id="usuario"  usuario='user'>
                        <div style="margin-bottom:0px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input id="usuario" name="usuario" type="text" class="form-control" value="" 
                                   placeholder="<?php echo __('Usuario') ?>" required class="form-control input-lg" autofocus="">    
                        </div>                       
                    </div>     
                </div>
            </div>
        </div>
        <!--Contraseña-->
        </br>
        <div class="row">
            <!--LABEL-->
            <div class="col-md-6 col-md-offset-3 col-xs-12">
                <div class="col-xs-12 col-sm-2">
                </div>
                <!--Caja de texto-->
                <div class="col-xs-12 col-sm-9">                    
                    <div id="pass_div"  pass='pass'>
                        <div style="margin-bottom: 10px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input id="password" name="password" type="password" class="form-control"
                                   name="password" placeholder="<?php echo __('Contraseña') ?>" required="" >
                        </div>   
                    </div>     
                </div>                 
            </div>   
        </div>
        <!--Botonera-->
        </br>
        <div class="col-md-6 col-md-offset-3 col-xs-12">
            <div class="col-xs-12 col-sm-2">
            </div>
            <!--Boton-->
            <div class="col-xs-12 col-sm-9">
                <div id="pass_div"  pass='pass'>
                    <input id="aceptar_login" login="licencias" type="submit" 
                           class="btn btn-primary btn-block" value="<?php echo __('Aceptar') ?>" />
                </div>  
            </div>                
        </div>         
    </div>
    </br>
    <div class="text-center">
        <a href="<?php echo $this->url(array('action' => 'recuperar', 'controller' => 'usuarios')) ?>" tabindex="5" class="forgot-password"><?php echo __('Olvido Contraseña?') ?></a>
    </div>
</form>