<a href="<?php echo $this->url(array('action' => 'alta')) ?>" class="btn btn-primary">Nuevo</a>

<table class="table">
    <tr>
        <td><?php echo __('Nombre') ?></td>
        <td><?php echo __('Acciones') ?></td>
    </tr>
    <?php foreach ($this->listado as $usuario) : ?>
        <tr>
            <td>
                <?php echo $usuario->getUsuario(); ?>
            </td>
            <td>
                <a href="<?php echo $this->url(array('action' => 'modificar', 'id' => $usuario->getId())) ?>"><?php echo __('Editar') ?></a>
                <a href="<?php echo $this->url(array('action' => 'baja', 'id' => $usuario->getId())) ?>"><?php echo __('Borrar') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>